// (this file was autogenerated by `generate-locales`)
// "plural rules" functions are not stored in locale JSON files because they're not strings.
// This file isn't big — it's about 5 kilobytes in size (minified).
// Alternatively, the pluralization rules for each locale could be stored
// in their JSON files in a non-parsed form and later parsed via `make-plural` library.
// But `make-plural` library itself is relatively big in size:
// `make-plural.min.js` is about 6 kilobytes (https://unpkg.com/make-plural/).
// So, it's more practical to bypass runtime `make-plural` pluralization rules compilation
// and just include the already compiled pluarlization rules for all locales in the library code.

var $ = {
	af: function(n
	) {
		return (n == 1) ? 'one' : 'other';
	},
	ak: function(n
	) {
		return ((n == 0
						|| n == 1)) ? 'one' : 'other';
	},
	am: function(n
	) {
		return (n >= 0 && n <= 1) ? 'one' : 'other';
	},
	ar: function(n
	) {
		var s = String(n).split('.'), t0 = Number(s[0]) == n,
				n100 = t0 && s[0].slice(-2);
		return (n == 0) ? 'zero'
				: (n == 1) ? 'one'
				: (n == 2) ? 'two'
				: ((n100 >= 3 && n100 <= 10)) ? 'few'
				: ((n100 >= 11 && n100 <= 99)) ? 'many'
				: 'other';
	},
	ast: function(n
	) {
		var s = String(n).split('.'), v0 = !s[1];
		return (n == 1 && v0) ? 'one' : 'other';
	},
	be: function(n
	) {
		var s = String(n).split('.'), t0 = Number(s[0]) == n,
				n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
		return (n10 == 1 && n100 != 11) ? 'one'
				: ((n10 >= 2 && n10 <= 4) && (n100 < 12
						|| n100 > 14)) ? 'few'
				: (t0 && n10 == 0 || (n10 >= 5 && n10 <= 9)
						|| (n100 >= 11 && n100 <= 14)) ? 'many'
				: 'other';
	},
	bm: function(n
	) {
		return 'other';
	},
	br: function(n
	) {
		var s = String(n).split('.'), t0 = Number(s[0]) == n,
				n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2),
				n1000000 = t0 && s[0].slice(-6);
		return (n10 == 1 && n100 != 11 && n100 != 71 && n100 != 91) ? 'one'
				: (n10 == 2 && n100 != 12 && n100 != 72 && n100 != 92) ? 'two'
				: (((n10 == 3 || n10 == 4) || n10 == 9) && (n100 < 10
						|| n100 > 19) && (n100 < 70 || n100 > 79) && (n100 < 90
						|| n100 > 99)) ? 'few'
				: (n != 0 && t0 && n1000000 == 0) ? 'many'
				: 'other';
	},
	bs: function(n
	) {
		var s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1],
				i10 = i.slice(-1), i100 = i.slice(-2), f10 = f.slice(-1), f100 = f.slice(-2);
		return (v0 && i10 == 1 && i100 != 11
						|| f10 == 1 && f100 != 11) ? 'one'
				: (v0 && (i10 >= 2 && i10 <= 4) && (i100 < 12 || i100 > 14)
						|| (f10 >= 2 && f10 <= 4) && (f100 < 12
						|| f100 > 14)) ? 'few'
				: 'other';
	},
	cs: function(n
	) {
		var s = String(n).split('.'), i = s[0], v0 = !s[1];
		return (n == 1 && v0) ? 'one'
				: ((i >= 2 && i <= 4) && v0) ? 'few'
				: (!v0) ? 'many'
				: 'other';
	},
	cy: function(n
	) {
		return (n == 0) ? 'zero'
				: (n == 1) ? 'one'
				: (n == 2) ? 'two'
				: (n == 3) ? 'few'
				: (n == 6) ? 'many'
				: 'other';
	},
	da: function(n
	) {
		var s = String(n).split('.'), i = s[0], t0 = Number(s[0]) == n;
		return (n == 1 || !t0 && (i == 0
						|| i == 1)) ? 'one' : 'other';
	},
	dsb: function(n
	) {
		var s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1],
				i100 = i.slice(-2), f100 = f.slice(-2);
		return (v0 && i100 == 1
						|| f100 == 1) ? 'one'
				: (v0 && i100 == 2
						|| f100 == 2) ? 'two'
				: (v0 && (i100 == 3 || i100 == 4) || (f100 == 3
						|| f100 == 4)) ? 'few'
				: 'other';
	},
	ff: function(n
	) {
		return (n >= 0 && n < 2) ? 'one' : 'other';
	},
	fil: function(n
	) {
		var s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1],
				i10 = i.slice(-1), f10 = f.slice(-1);
		return (v0 && (i == 1 || i == 2 || i == 3)
						|| v0 && i10 != 4 && i10 != 6 && i10 != 9
						|| !v0 && f10 != 4 && f10 != 6 && f10 != 9) ? 'one' : 'other';
	},
	ga: function(n
	) {
		var s = String(n).split('.'), t0 = Number(s[0]) == n;
		return (n == 1) ? 'one'
				: (n == 2) ? 'two'
				: ((t0 && n >= 3 && n <= 6)) ? 'few'
				: ((t0 && n >= 7 && n <= 10)) ? 'many'
				: 'other';
	},
	gd: function(n
	) {
		var s = String(n).split('.'), t0 = Number(s[0]) == n;
		return ((n == 1
						|| n == 11)) ? 'one'
				: ((n == 2
						|| n == 12)) ? 'two'
				: (((t0 && n >= 3 && n <= 10)
						|| (t0 && n >= 13 && n <= 19))) ? 'few'
				: 'other';
	},
	gv: function(n
	) {
		var s = String(n).split('.'), i = s[0], v0 = !s[1], i10 = i.slice(-1),
				i100 = i.slice(-2);
		return (v0 && i10 == 1) ? 'one'
				: (v0 && i10 == 2) ? 'two'
				: (v0 && (i100 == 0 || i100 == 20 || i100 == 40 || i100 == 60
						|| i100 == 80)) ? 'few'
				: (!v0) ? 'many'
				: 'other';
	},
	he: function(n
	) {
		var s = String(n).split('.'), i = s[0], v0 = !s[1], t0 = Number(s[0]) == n,
				n10 = t0 && s[0].slice(-1);
		return (n == 1 && v0) ? 'one'
				: (i == 2 && v0) ? 'two'
				: (v0 && (n < 0
						|| n > 10) && t0 && n10 == 0) ? 'many'
				: 'other';
	},
	is: function(n
	) {
		var s = String(n).split('.'), i = s[0], t0 = Number(s[0]) == n,
				i10 = i.slice(-1), i100 = i.slice(-2);
		return (t0 && i10 == 1 && i100 != 11
						|| !t0) ? 'one' : 'other';
	},
	iu: function(n
	) {
		return (n == 1) ? 'one'
				: (n == 2) ? 'two'
				: 'other';
	},
	ksh: function(n
	) {
		return (n == 0) ? 'zero'
				: (n == 1) ? 'one'
				: 'other';
	},
	lag: function(n
	) {
		var s = String(n).split('.'), i = s[0];
		return (n == 0) ? 'zero'
				: ((i == 0
						|| i == 1) && n != 0) ? 'one'
				: 'other';
	},
	lt: function(n
	) {
		var s = String(n).split('.'), f = s[1] || '', t0 = Number(s[0]) == n,
				n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
		return (n10 == 1 && (n100 < 11
						|| n100 > 19)) ? 'one'
				: ((n10 >= 2 && n10 <= 9) && (n100 < 11
						|| n100 > 19)) ? 'few'
				: (f != 0) ? 'many'
				: 'other';
	},
	lv: function(n
	) {
		var s = String(n).split('.'), f = s[1] || '', v = f.length,
				t0 = Number(s[0]) == n, n10 = t0 && s[0].slice(-1),
				n100 = t0 && s[0].slice(-2), f100 = f.slice(-2), f10 = f.slice(-1);
		return (t0 && n10 == 0 || (n100 >= 11 && n100 <= 19)
						|| v == 2 && (f100 >= 11 && f100 <= 19)) ? 'zero'
				: (n10 == 1 && n100 != 11 || v == 2 && f10 == 1 && f100 != 11
						|| v != 2 && f10 == 1) ? 'one'
				: 'other';
	},
	mk: function(n
	) {
		var s = String(n).split('.'), i = s[0], f = s[1] || '', v0 = !s[1],
				i10 = i.slice(-1), i100 = i.slice(-2), f10 = f.slice(-1), f100 = f.slice(-2);
		return (v0 && i10 == 1 && i100 != 11
						|| f10 == 1 && f100 != 11) ? 'one' : 'other';
	},
	mo: function(n
	) {
		var s = String(n).split('.'), v0 = !s[1], t0 = Number(s[0]) == n,
				n100 = t0 && s[0].slice(-2);
		return (n == 1 && v0) ? 'one'
				: (!v0 || n == 0
						|| n != 1 && (n100 >= 1 && n100 <= 19)) ? 'few'
				: 'other';
	},
	mt: function(n
	) {
		var s = String(n).split('.'), t0 = Number(s[0]) == n,
				n100 = t0 && s[0].slice(-2);
		return (n == 1) ? 'one'
				: (n == 0
						|| (n100 >= 2 && n100 <= 10)) ? 'few'
				: ((n100 >= 11 && n100 <= 19)) ? 'many'
				: 'other';
	},
	pl: function(n
	) {
		var s = String(n).split('.'), i = s[0], v0 = !s[1], i10 = i.slice(-1),
				i100 = i.slice(-2);
		return (n == 1 && v0) ? 'one'
				: (v0 && (i10 >= 2 && i10 <= 4) && (i100 < 12
						|| i100 > 14)) ? 'few'
				: (v0 && i != 1 && (i10 == 0 || i10 == 1)
						|| v0 && (i10 >= 5 && i10 <= 9)
						|| v0 && (i100 >= 12 && i100 <= 14)) ? 'many'
				: 'other';
	},
	pt: function(n
	) {
		var s = String(n).split('.'), i = s[0];
		return ((i == 0
						|| i == 1)) ? 'one' : 'other';
	},
	ru: function(n
	) {
		var s = String(n).split('.'), i = s[0], v0 = !s[1], i10 = i.slice(-1),
				i100 = i.slice(-2);
		return (v0 && i10 == 1 && i100 != 11) ? 'one'
				: (v0 && (i10 >= 2 && i10 <= 4) && (i100 < 12
						|| i100 > 14)) ? 'few'
				: (v0 && i10 == 0 || v0 && (i10 >= 5 && i10 <= 9)
						|| v0 && (i100 >= 11 && i100 <= 14)) ? 'many'
				: 'other';
	},
	shi: function(n
	) {
		var s = String(n).split('.'), t0 = Number(s[0]) == n;
		return (n >= 0 && n <= 1) ? 'one'
				: ((t0 && n >= 2 && n <= 10)) ? 'few'
				: 'other';
	},
	si: function(n
	) {
		var s = String(n).split('.'), i = s[0], f = s[1] || '';
		return ((n == 0 || n == 1)
						|| i == 0 && f == 1) ? 'one' : 'other';
	},
	sl: function(n
	) {
		var s = String(n).split('.'), i = s[0], v0 = !s[1], i100 = i.slice(-2);
		return (v0 && i100 == 1) ? 'one'
				: (v0 && i100 == 2) ? 'two'
				: (v0 && (i100 == 3 || i100 == 4)
						|| !v0) ? 'few'
				: 'other';
	},
	tzm: function(n
	) {
		var s = String(n).split('.'), t0 = Number(s[0]) == n;
		return ((n == 0 || n == 1)
						|| (t0 && n >= 11 && n <= 99)) ? 'one' : 'other';
	}
}

$.ars = $.ar
$.as = $.am
$.asa = $.af
$.az = $.af
$.bem = $.af
$.bez = $.af
$.bg = $.af
$.bh = $.ak
$.bn = $.am
$.bo = $.bm
$.brx = $.af
$.ca = $.ast
$.ce = $.af
$.cgg = $.af
$.chr = $.af
$.ckb = $.af
$.de = $.ast
$.dv = $.af
$.dz = $.bm
$.ee = $.af
$.el = $.af
$.en = $.ast
$.eo = $.af
$.es = $.af
$.et = $.ast
$.eu = $.af
$.fa = $.am
$.fi = $.ast
$.fo = $.af
$.fr = $.ff
$.fur = $.af
$.fy = $.ast
$.gl = $.ast
$.gsw = $.af
$.gu = $.am
$.guw = $.ak
$.ha = $.af
$.haw = $.af
$.hi = $.am
$.hr = $.bs
$.hsb = $.dsb
$.hu = $.af
$.hy = $.ff
$.ia = $.ast
$.id = $.bm
$.ig = $.bm
$.ii = $.bm
$.in = $.bm
$.io = $.ast
$.it = $.ast
$.iw = $.he
$.ja = $.bm
$.jbo = $.bm
$.jgo = $.af
$.ji = $.ast
$.jmc = $.af
$.jv = $.bm
$.jw = $.bm
$.ka = $.af
$.kab = $.ff
$.kaj = $.af
$.kcg = $.af
$.kde = $.bm
$.kea = $.bm
$.kk = $.af
$.kkj = $.af
$.kl = $.af
$.km = $.bm
$.kn = $.am
$.ko = $.bm
$.ks = $.af
$.ksb = $.af
$.ku = $.af
$.kw = $.iu
$.ky = $.af
$.lb = $.af
$.lg = $.af
$.lkt = $.bm
$.ln = $.ak
$.lo = $.bm
$.mas = $.af
$.mg = $.ak
$.mgo = $.af
$.ml = $.af
$.mn = $.af
$.mr = $.am
$.ms = $.bm
$.my = $.bm
$.nah = $.af
$.naq = $.iu
$.nb = $.af
$.nd = $.af
$.ne = $.af
$.nl = $.ast
$.nn = $.af
$.nnh = $.af
$.no = $.af
$.nqo = $.bm
$.nr = $.af
$.nso = $.ak
$.ny = $.af
$.nyn = $.af
$.om = $.af
$.or = $.af
$.os = $.af
$.pa = $.ak
$.pap = $.af
$.prg = $.lv
$.ps = $.af
$["pt-PT"] = $.ast
$.rm = $.af
$.ro = $.mo
$.rof = $.af
$.root = $.bm
$.rwk = $.af
$.sah = $.bm
$.saq = $.af
$.sc = $.ast
$.scn = $.ast
$.sd = $.af
$.sdh = $.af
$.se = $.iu
$.seh = $.af
$.ses = $.bm
$.sg = $.bm
$.sh = $.bs
$.sk = $.cs
$.sma = $.iu
$.smi = $.iu
$.smj = $.iu
$.smn = $.iu
$.sms = $.iu
$.sn = $.af
$.so = $.af
$.sq = $.af
$.sr = $.bs
$.ss = $.af
$.ssy = $.af
$.st = $.af
$.sv = $.ast
$.sw = $.ast
$.syr = $.af
$.ta = $.af
$.te = $.af
$.teo = $.af
$.th = $.bm
$.ti = $.ak
$.tig = $.af
$.tk = $.af
$.tl = $.fil
$.tn = $.af
$.to = $.bm
$.tr = $.af
$.ts = $.af
$.ug = $.af
$.uk = $.ru
$.ur = $.ast
$.uz = $.af
$.ve = $.af
$.vi = $.bm
$.vo = $.af
$.vun = $.af
$.wa = $.ak
$.wae = $.af
$.wo = $.bm
$.xh = $.af
$.xog = $.af
$.yi = $.ast
$.yo = $.bm
$.yue = $.bm
$.zh = $.bm
$.zu = $.am

export default $